# Generated by Django 3.0.5 on 2020-06-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='landmark',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
