# Generated by Django 3.1.2 on 2020-12-08 06:15

from django.db import migrations, models
import django.db.models.deletion
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.state'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
