# Generated by Django 3.1.2 on 2020-12-10 06:17

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20201210_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaperone',
            old_name='is_user',
            new_name='is_attendant',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
