# Generated by Django 3.1.2 on 2020-12-09 17:58

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20201209_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
