# Generated by Django 3.0.5 on 2020-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200628_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='city',
            field=models.CharField(choices=[('', 'Choose...'), ('ar', 'Ara'), ('blr', 'Bangalore'), ('mb', 'Mumbai'), ('nd', 'Noida')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(choices=[('', 'Choose...'), ('nr', 'Nursing'), ('vc', 'Vaccination'), ('ec', 'Elder care'), ('dc', 'Doctor consultation'), ('md', 'Medicine delivery'), ('ndc', 'Nutrition & Diet consultation'), ('am', 'Ambulance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='state',
            field=models.CharField(choices=[('', 'Choose...'), ('br', 'Bihar'), ('ka', 'Karnataka'), ('mh', 'Maharashtra'), ('up', 'UP')], max_length=100),
        ),
    ]
