# Generated by Django 3.1.2 on 2020-12-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201220_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.vendoruser'),
        ),
    ]
