# Generated by Django 3.1.2 on 2020-12-10 06:18

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201210_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaperone',
            name='is_attendant',
        ),
        migrations.RemoveField(
            model_name='vendoruser',
            name='is_vendor',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
