# Generated by Django 3.1.2 on 2020-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200628_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='city',
            field=models.CharField(choices=[('', 'Choose...'), ('ar', 'Patna'), ('blr', 'Bangalore'), ('mb', 'Mumbai'), ('nd', 'Noida')], max_length=100),
        ),
    ]
