# Generated by Django 3.1.2 on 2020-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_vendorservice_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorservice',
            name='registered_by',
            field=models.CharField(default='None', max_length=155),
        ),
    ]
