# Generated by Django 3.1.2 on 2020-12-10 09:20

from django.db import migrations, models
import django.db.models.deletion
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20201210_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='holder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.chaperone'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
