# Generated by Django 3.1.2 on 2020-12-10 15:01

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20201210_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
