# Generated by Django 3.1.2 on 2021-01-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20210109_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreport',
            name='paddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='pcity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='pcontact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='pname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ppin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='pstate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
