# Generated by Django 3.1.2 on 2020-12-10 15:50

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20201210_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
