# Generated by Django 3.1.2 on 2021-01-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20210109_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
