# Generated by Django 3.1.2 on 2020-12-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20201210_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='holder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(default=None, upload_to=src.models.content_file_name),
        ),
    ]
