# Generated by Django 3.1.2 on 2021-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20210109_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
