# Generated by Django 3.1.2 on 2021-01-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20210110_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.patient'),
        ),
    ]
